In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[9864, 6094, 4331, 9360],
 [9864, 6094, 4331, 4950],
 [9864, 3352, 4331, 8321],
 [4326, 1018, 8170, 2060, 871],
 [4326, 1018, 8170, 2060, 6660],
 [3456, 9864, 7908, 4331, 8031],
 [2364, 5217, 638, 2060]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 9864 6094 4331 9360]
 [   0    0    0    0 9864 6094 4331 4950]
 [   0    0    0    0 9864 3352 4331 8321]
 [   0    0    0 4326 1018 8170 2060  871]
 [   0    0    0 4326 1018 8170 2060 6660]
 [   0    0    0 3456 9864 7908 4331 8031]
 [   0    0    0    0 2364 5217  638 2060]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 107ms/step


array([[[-3.02153826e-03,  3.75071429e-02, -3.49992998e-02,
         -2.20166687e-02, -1.85756907e-02,  1.82148330e-02,
         -3.36302891e-02, -2.85711177e-02,  3.17468382e-02,
         -4.05701622e-02],
        [-3.02153826e-03,  3.75071429e-02, -3.49992998e-02,
         -2.20166687e-02, -1.85756907e-02,  1.82148330e-02,
         -3.36302891e-02, -2.85711177e-02,  3.17468382e-02,
         -4.05701622e-02],
        [-3.02153826e-03,  3.75071429e-02, -3.49992998e-02,
         -2.20166687e-02, -1.85756907e-02,  1.82148330e-02,
         -3.36302891e-02, -2.85711177e-02,  3.17468382e-02,
         -4.05701622e-02],
        [-3.02153826e-03,  3.75071429e-02, -3.49992998e-02,
         -2.20166687e-02, -1.85756907e-02,  1.82148330e-02,
         -3.36302891e-02, -2.85711177e-02,  3.17468382e-02,
         -4.05701622e-02],
        [ 2.20767148e-02,  1.98619701e-02,  2.72926800e-02,
         -3.30646038e-02,  4.01766039e-02,  2.75510214e-02,
         -9.83763859e-03, -4.93100062e-02, -4.184149

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 9864, 6094, 4331, 9360])

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 48ms/step


array([[-0.00302154,  0.03750714, -0.0349993 , -0.02201667, -0.01857569,
         0.01821483, -0.03363029, -0.02857112,  0.03174684, -0.04057016],
       [-0.00302154,  0.03750714, -0.0349993 , -0.02201667, -0.01857569,
         0.01821483, -0.03363029, -0.02857112,  0.03174684, -0.04057016],
       [-0.00302154,  0.03750714, -0.0349993 , -0.02201667, -0.01857569,
         0.01821483, -0.03363029, -0.02857112,  0.03174684, -0.04057016],
       [-0.00302154,  0.03750714, -0.0349993 , -0.02201667, -0.01857569,
         0.01821483, -0.03363029, -0.02857112,  0.03174684, -0.04057016],
       [ 0.02207671,  0.01986197,  0.02729268, -0.0330646 ,  0.0401766 ,
         0.02755102, -0.00983764, -0.04931001, -0.00418415, -0.03698424],
       [ 0.01659321, -0.02370341,  0.01446814, -0.02175272,  0.0493572 ,
         0.0438757 , -0.03062937, -0.04786824,  0.03753005,  0.02414459],
       [-0.02039225,  0.01321932,  0.04784887,  0.01536452, -0.00600405,
        -0.03092504, -0.04956789,  0.04131616